#! /bin/sh
# Exports
# export XDG_CONFIG_HOME="$HOME/.config"
# export SSH_AUTH_SOCK
# export $BROWSER=google-chrome-stable
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# pywal
wal -R
. "${HOME}/.cache/wal/colors.sh"

# keyboard repeat rate
xset r rate 350 60
# cursor pointer
xsetroot -cursor_name left_ptr
# screen saving
xset dpms 600 900 1200

# keybinds
sxhkd &

# beauty
~/.config/polybar/launch.sh &

# ibus
ibus-daemon -xdr &

# pywal
bspc config normal_border_color "transparent"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config remove_unplugged_monitors true

bspc rule -a Screenkey manage=off

