address_family = both
encoder = vaapi
global_prep_cmd = [{"do":"/home/tn/.local/bin/sunshine-stream-prep","undo":"/home/tn/.local/bin/sunshine-stream-undo"}]
minimum_fps_target = 60
upnp = enabled
wan_encryption_mode = 0
